version: 2.1

orbs: 
  win: circleci/windows@4.1.1

commands:
  generate-and-upload-executable:
    parameters:
      artifact_location:
        type: string
        default: target/release/proxybroker
    steps:
      - run:
          name: Rust Version
          command: rustc --version
      - run:
          name: Build Artifact
          command: cargo build --release
      - run:
          name: Strip Executable
          command: upx --best --lzma << parameters.artifact_location >>
      - store_artifacts:
          path: << parameters.artifact_location >>

jobs:
  build-linux:
    working_directory: ~/proxybroker
    docker:
      - image: cimg/rust:1.63.0
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install UPX
          command: sudo apt-get update && sudo apt-get install -y upx
      - generate-and-upload-executable
  build-macos:
    working_directory: ~/proxybroker
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: Install Rustup
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          name: Install UPX
          command: brew install upx
      - generate-and-upload-executable
  build-windows:
    working_directory: ~/proxybroker
    executor: 
      name: win/default
      size: large
    steps:
      - checkout
      - run:
          name: Install Rustup
          command: Start-BitsTransfer -Source "https://win.rustup.rs/x86_64" -Destination "rustup-init.exe"
      - run:
          name: Run rustup init
          command: .\rustup-init.exe -y
      - run: 
          name: Change Rust ToolChain to x84_64 windows msvc
          command: rustup default stable-x86_64-pc-windows-msvc
      - run:
          name: Install UPX
          command: choco install -y upx
      - generate-and-upload-executable:
          artifact_location: 'target/release/proxybroker.exe'

workflows:
  build-executables:
    jobs:
      - build-linux
      - build-macos
      - build-windows