name: 'Build ProxyBroker'
description: 'Build Golang ProxyBroker project'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
runs:
  using: 'docker'
  image: 'Dockerfile'