name: 'Build ProxyBroker'
description: 'Build Golang ProxyBroker project'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build ProxyChecker on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    using: 'docker'
    image: 'Dockerfile'
    steps:
     - name: Archive code
       uses: actions/upload-artifact@v2
       with:
        name: build-artifacts
        path: './ProxyBroker*'