# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Golang Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build ProxyChecker on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Golang 17
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - name: Build with Golang
        run: cd src && bash ../build.bash github.com/Ziloka/ProxyBroker bleeding-release
      # - name: Minimize Linux Executable Size (Strip debug data)
      #   run: strip --strip-all src/ProxyBroker-linux-amd64 & strip --strip-all src/ProxyBroker-windows-amd64.exe
      - name: Install UPX 3.96
        run: sudo apt-get install wget && wget http://archive.ubuntu.com/ubuntu/pool/universe/u/upx-ucl/upx-ucl_3.96-2_amd64.deb && dpkg -i upx-ucl_3.96-2_amd64.deb && upx --version
      - name: Pack Executables
        run: upx --best --lzma src/ProxyBroker-linux-amd64 & upx --best --lzma src/ProxyBroker-darwin-amd64 & upx --best --lzma src/ProxyBroker-windows-amd64.exe
      - name: Upload Executables
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: './src/ProxyBroker*'
